#! /usr/bin/env python3

from collections import Counter
import sys

for k, v in Counter(open(0, "rb").read().splitlines()).most_common():
    sys.stdout.buffer.write(bytes(str(v), "ascii") + b" " + k + b"\n")
