#! /usr/bin/env python3
# coding: utf-8


def human_bytes(num, suffix="B"):
    for unit in ["", "Ki", "Mi", "Gi", "Ti", "Pi", "Ei", "Zi"]:
        if abs(num) < 1024.0:
            return f"{num:3.1f}{unit}{suffix}"
        num /= 1024.0
    return f"{num:.1f}Yi{suffix}"


for l in open(0).read().splitlines():
    num = int(l)
    print(human_bytes(num))
