#!/usr/bin/env python3
from __future__ import annotations

import sys

b = r'\b'
if sys.argv[1:2] == ['-n']:
    b = ''

parts = [f"{b}({line.rstrip('\n')}){b}" for line in open(0)]
print('|'.join(parts))
