#! /bin/bash
set -CEeu

export MSYS2_ARG_CONV_EXCL='*'

cer_path="${1:-mitmproxy-ca-cert.cer}"
cert_hash="$(openssl x509 -inform PEM -subject_hash_old -in "$cer_path" | head -1)"
cert_fname="$cert_hash.0"
cp "$cer_path" "$cert_fname"

adb.exe root
adb.exe shell "mount -o rw,remount /"
adb.exe push "$cert_fname" /system/etc/security/cacerts
adb.exe shell "chmod 664 /system/etc/security/cacerts/$cert_fname"
echo "adb reboot"
rm "$cert_fname"
