#!/usr/bin/env python3
# coding: utf-8

from posixpath import dirname
from os.path import exists, join, splitext, basename
from subprocess import run
from sys import stdout, argv

EXT = "webm"
for f in argv[1:]:
    stem, orig_ext = splitext(basename(f))
    if orig_ext == EXT:
        print(f"skip {basename(f)}")
        continue

    out = join(dirname(f), f"{stem}.{EXT}")

    cmd = [
        "ffmpeg.exe",
        "-i",
        f,
        "-c:v",
        "libvpx-vp9",
        "-minrate",
        "500k",
        "-b:v",
        "2000k",
        "-maxrate",
        "2500k",
        out,
    ]

    print(cmd)
    r = run(cmd, stdout=stdout)
