#!/usr/bin/env python3
# coding: utf-8

from __future__ import annotations
import sys
import operator
from functools import reduce


def op2func(op: str):
    func = None
    if op in ("+", "s", "sum", "summaly", "add"):
        func = operator.add
    elif op in ("*", "m", "mul", "multiply", "product"):
        func = operator.mul
    return func


def get_nums() -> list[float]:
    lines = open(0).read().splitlines()

    tmp = [e.strip().split(" ") for e in lines if e]
    tmp = reduce(lambda a, b: a + b, tmp)
    tmp = map(float, tmp)

    return list(tmp)


def get_func():
    op = sys.argv[1]
    func = op2func(op)
    if func is None:
        raise ValueError(func)
    return func


print(reduce(get_func(), get_nums()))
