#!/usr/bin/env bash
# Original: https://codeberg.org/EvanHahn/dotfiles/src/commit/843b9ee13d949d346a4a73ccee2a99351aed285b/home/bin/bin/pasta
set -e
set -u

if hash win32yank.exe 2>/dev/null; then
  exec win32yank.exe -o
elif hash pbpaste 2>/dev/null; then
  exec pbpaste
elif hash xclip 2>/dev/null; then
  exec xclip -selection clipboard -o
elif [[ -e /tmp/clipboard ]]; then
  exec cat /tmp/clipboard
else
  echo ''
fi
