#!/usr/bin/env python3
# coding: utf-8

# nvimから使う

# echo 'types["$_"] = 1;' > tmp
# echo "BIGINT" >> tmp
# echo "BIG_DECIMAL" >> tmp
# ./template < tmp

from __future__ import annotations
import sys

sep = sys.argv[1] if len(sys.argv) > 1 else " "

template = sys.stdin.readline().rstrip()

if "$" not in template:
    raise RuntimeError(
        f"1行目はテンプレートだよ。テンプレートには $1, $2, ... を含んでないといけないんだ ;ω;"
    )

# ٩( ᐛ )و
for line in sys.stdin:
    result = template
    if "$_" in template:
        result = result.replace("$_", line.rstrip())
    else:
        for i, word in enumerate(line.rstrip().split(sep), start=1):
            result = result.replace(f"${i}", word)
    print(result)

# ٩( ᐛ )و
