#!/usr/bin/env python3
# coding: utf-8

from __future__ import annotations
from publicsuffix2 import fetch, get_sld, get_tld

import sys
try:
    level = int(sys.argv[1])
except:
    level = 1

f = get_tld
if level == 1:
    f = get_tld
elif level == 3:
    f = get_sld


print("\n".join(f(s) or s for s in open(0).read().splitlines()))
