#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "requests==2.32.4",
#   "requests_oauthlib==2.0.0",
#   "publicsuffix2==2.20191221"
# ]
# ///
# coding: utf-8

from __future__ import annotations
from publicsuffix2 import fetch, get_sld, get_tld

import sys
try:
    level = int(sys.argv[1])
except:
    level = 1

f = get_tld
if level == 1:
    f = get_tld
elif level == 3:
    f = get_sld


def trim_start(s: str, needle: str) -> str:
    if s.startswith(needle):
        return s[len(needle) :]
    else:
        return s


def trim_end(s: str, needle: str) -> str:
    if s.endswith(needle):
        return s[: -len(needle)]
    else:
        return s

def proccess(s:str):
    s = trim_start(s, "https://")
    s = trim_start(s, "http://")
    p = s.find("/")
    if p>=0:
        s = s[:p]
    return s


print("\n".join(f(proccess(s)) or s for s in open(0).read().splitlines()))
