#!/usr/bin/env python3
# coding: utf-8
import __future__
import sys

if len(sys.argv) >= 2 and sys.argv[1] == "-w":
    # 空白を無視する
    import re

    skip = re.compile(r"^\r?\n|^#|^$")

    s = set()
    for r in open(0).read().splitlines():
        if skip.match(r) is None:
            if r in s:
                continue
        s.add(r)
        print(r)
else:
    s = set()
    for r in open(0).read().splitlines():
        if r in s:
            continue
        s.add(r)
        print(r)
