#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o pipefail -o nounset

cd "$(dirname "$0")"

PORT=$1
WIN_TO_WSL=${2:-1}
WSL_TO_WIN=${3:-0}

HOST_IPV4=$(powershell.exe -Command "Get-NetIPAddress | Where-Object { \
  \$_.AddressFamily -eq 'IPv4' -and \
  \$_.InterfaceAlias -notmatch 'Loopback|WSL' -and \
  \$_.AddressState -eq 'Preferred' -and \
  \$_.IPAddress -notmatch '^169\.254\.' \
} | Select-Object -ExpandProperty IPAddress" | tr -d '\r')

WSL2_IPV4=$(ip address show eth0 | awk '/inet / {print $2}' | awk -F / '{print $1}')
#WSL2_IPV4=$(ip route | awk '/default/ {print $3}')

if [[ $WIN_TO_WSL -eq 1 ]]; then
  echo "portfoward $HOST_IPV4:$PORT -> $WSL2_IPV4:$PORT"
  gsudo netsh.exe interface portproxy add v4tov4 \
    listenaddress="$HOST_IPV4" \
    listenport="$PORT" \
    connectaddress="$WSL2_IPV4" \
    connectport="$PORT"
fi

if [[ $WSL_TO_WIN -eq 1 ]]; then
  echo "portfoward $HOST_IPV4:$PORT <- $WSL2_IPV4:$PORT"
  gsudo netsh.exe interface portproxy add v4tov4 \
    listenaddress="$WSL2_IPV4" \
    listenport="$PORT" \
    connectaddress="$HOST_IPV4" \
    connectport="$PORT"
fi
