#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "jaconv==0.4.0",
# ]
# ///
# coding: utf-8
import jaconv

s = open(0).read()
print(jaconv.z2h(s, kana=False, ascii=True, digit=True))
